### ISSUE TITLE
Blazor.Extensions.Logging fails to build

### ISSUE THREAD

**Issue by ninjasource** [BlazorExtensions/Logging#17]
Hi I have downloaded your solution from github as a zip file, decompressed it, opened the solution file and built the project. Unfortunately it does not build out of the box.

This is what happens when you attempt to build the project Blazor.Extensions.Logging:
Error	MSB3073	The command "git rev-parse --show-toplevel" exited with code 128.	Blazor.Extensions.Logging	C:\Users\xxxxx\.nuget\packages\sourcelink.create.commandline\2.8.3\build\SourceLink.Create.CommandLine.targets	21	

And this is what happens when you attempt to remove the SourceLink dependency using nuget package manager
Error		Cannot modify an evaluated object originating in an imported file "C:\Users\xxxxxx\Logging-master\Logging-master\src\Directory.Build.targets".			

I also get a bunch of yellow warning triangles on the dependencies. Both nuget and the SDK. Have you built this project with some special setup? If so, could you please let me know how to build it. 
Thanks.

**Comment by galvesribeiro** [comment]
Hey @ninjasource 

You need to clone the repo, not download the zip. We use Source link and git hashs on build. You can build without it but you will need to remove a lot of things from the solution and change others. It is easier to just clone the repo.

There no special tooling. All you need is the .Net Core SDK and NodeJS.

Let me know if you have any further issues.

Thanks!

**Comment by ninjasource** [comment]
Great, thanks for the help!
