### ISSUE TITLE
V 0.1.10 for Blazor V3.0P4 has reference to old package, produces compile time error

### ISSUE THREAD

**Issue by BillHertzing** [BlazorExtensions/Logging#26]
I tried adding V0.1.10 to a project that worked with the logging library a few revisions ago. I get an error 
![image](https://user-images.githubusercontent.com/894644/57006386-9c6df480-6b9d-11e9-8bdf-5de33b8ac9ab.png), and I noticed the package references an old blazor assembly

![image](https://user-images.githubusercontent.com/894644/57006391-ae4f9780-6b9d-11e9-9438-1774f6d2edde.png)

perhaps some package references are out of date?

**Comment by chucker** [comment]
The current released NuGet package requires Blazor 0.7. There’ll be an update soon.

**Comment by galvesribeiro** [comment]
Updated to preview4 now, can you try again? Will re-open if you still have issues. Thanks
