### ISSUE TITLE
V0.1.11 fails to write to Chrome Console 

### ISSUE THREAD

**Issue by BillHertzing** [BlazorExtensions/Logging#27]
Tested V0.1.11 today. It works in Firefox V66.0.3. It does not work in Chrome. My version of Chrome is Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by chucker** [comment]
Make sure your filters are set up correctly. This is probably the same issue as #16 and #7 — you need to actually ask Chrome to show verbose logs.

**Comment by BillHertzing** [comment]
Indeed. As mentioned in  issue #16, a note in the readme telling users about the difference between chrome and the others would be a good idea. Just copy in the verbiage and reference the image from #7. Such a note in the documentation would have saved me a quite a bit of time and saved the authors/maintainers from Yet Another Logged Issue That Is Actually A User Error :-). Thanks for this library!
