### ISSUE TITLE
Trace logs are freezing firefox

### ISSUE THREAD

**Issue by AndreasTruetschel** [BlazorExtensions/Logging#28]
Trace logs in the Firefox browser look very akward and eventually freeze the browser. This happens both, with server- and client-side blazor. A repro can be found [here](https://github.com/AndreasTruetschel/BlazorSignalR). 
The log looks like [firefox_tracelog.txt](https://github.com/BlazorExtensions/Logging/files/3210972/firefox_tracelog.txt)

**Comment by galvesribeiro** [comment]
Sorry but I have a very limited time to contribute to the OSS projects on BE and I can't help much if you are having problems with other SignalR implementations other than ours.

If you can make a repro case using the test projects on this repo, without anything else, then I can look at it.

I'm closing the issue for now. I'll re-open in case you have a clean repro.

Thanks
