### ISSUE TITLE
Show category?

### ISSUE THREAD

**Issue by dradovic** [BlazorExtensions/Logging#29]
Is there a way of showing the type passed into the logger as TCategoryName in the browser console?

**Comment by galvesribeiro** [comment]
Hello!

Categories are now being logged on https://www.nuget.org/packages/Blazor.Extensions.Logging/0.2.0 that should be available soon on Nuget.

![image](https://user-images.githubusercontent.com/4714040/61764342-3913ed00-adaf-11e9-8641-01f3b5696b0e.png)

The only exception is the logging of tables as the browser don't have parameters to it.

I'm closing the issue now. Please let me know if you find any issues. 

Thank yoU!
