### ISSUE TITLE
Microsoft.JSInterop.JSException: Could not find 'BlazorExtensions' in 'window'

### ISSUE THREAD

**Issue by brettwinters** [BlazorExtensions/Logging#41]
Hello

Just installed again after uninstalling while awaiting your update to preview 9, but I'm getting the above error in my console. 

Seems like its missing the js, but `Blazor.Extensions.Logging.JS.dll` is on the client..

Regards

Brett

**Comment by knight1219** [comment]
I'm getting this same error, just trying to run it locally. 
![image](https://user-images.githubusercontent.com/6771697/71825492-9f40b380-3061-11ea-93f2-36d031ddf0a9.png)

.net Core 3.1, tried with v1.0.0 and v1.1.0-preview2 of this lib with no luck.

**Comment by chucker** [comment]
@knight1219 3.1 isn't supported yet. Try adding `<script src="_content/blazor.extensions.logging.js"></script>` to your `index.html` somewhere inside `<head>`; that may be enough. If not, you'll have to wait for #49 or #51 to get merged.

**Comment by knight1219** [comment]
Can't find the js file, 404's. Is there any ETA on when this would get fixed? is there a way to manually generate the js file and add it to my project or a CDN as a workaround?

**Comment by attilah** [comment]
Closing as package is updated to Blazor RC1, available on [Nuget](https://www.nuget.org/packages/Blazor.Extensions.Logging/3.1.0-rc1-020501)
