### ISSUE TITLE
Log object to console

### ISSUE THREAD

**Issue by sebastianslutzky** [BlazorExtensions/Logging#46]
The wiki says it is possible to log an object, but I cannot see any example in the tests. I can't find the right api to do so either.

I am trying to get the same functionality you get in javascript when you print an object (Console.Log(anObjectOrSetOfObjects)) 
is this possible to do?

**Comment by chucker** [comment]
Haven't tried, but https://github.com/BlazorExtensions/Logging/blob/master/test/Blazor.Extensions.Logging.Test/Pages/Index.razor#L20 looks like an example of this.

Did you import the `Blazor.Extensions.Logging` namespace?

**Comment by sebastianslutzky** [comment]
yes, that did the trick, thanks! I was missing the import
