### ISSUE TITLE
log with LogDebug level are never printed in console.

### ISSUE THREAD

**Issue by dsaurel** [BlazorExtensions/Logging#7]
Hi, i'm using you nuget package with Blazor 0.4. I've encountered a strange behaviour.

In Program.cs, 
`// Add Blazor.Extensions.Logging.BrowserConsoleLogger
            services.AddLogging(builder => builder
                .AddBrowserConsole() // Register the logger with the ILoggerBuilder
                .SetMinimumLevel(LogLevel.Trace) // Set the minimum log level to Information
                );`

Then i injected logger in an hypothetical BlazorComponent:
`[Inject]
  private ILogger<IndexComponent> _logger { get; set; }`

Somewhere in a click triggered method:
```
_logger.LogDebug($"LogDebug {this.GetType().FullName}");
_logger.LogInformation($"LogInformation {this.GetType().FullName}");
_logger.LogWarning($"LogWarning {this.GetType().FullName}");
 _logger.LogTrace($"LogTrace {this.GetType().FullName}");
 _logger.LogCritical($"LogCritical {this.GetType().FullName}");
```

The message associated with logger.LogDebug is never printed in browser console.

Tested on Chrome Windows Version 67.0.3396.87 (Build officiel) (64 bits)

Thanks.

**Comment by attilah** [comment]
Hi @dsaurel!

This is not an issue with the logger, if you check in Edge or Firefox it just works.

The reason why you are not seeing it in Chrome is that from Chromium 58 the output of this method only appears when level [Verbose is selected in the DevTools](https://developer.mozilla.org/en-US/docs/Web/API/console).

![image](https://user-images.githubusercontent.com/230432/41523356-8f8c95d6-728e-11e8-951e-18c8676ed084.png)

After enabling it you see the expected output:

![image](https://user-images.githubusercontent.com/230432/41523409-c22ca4a4-728e-11e8-98a2-60dd3aa738c4.png)

**Comment by dsaurel** [comment]
Thanks 👍
